### ISSUE TITLE
Module doesn't work on Stage C

### ISSUE THREAD

**Issue by tlstoffs** [ctsit/prevent_past_or_future_dates#6] opened 2022-04-05 20:26 UTC
![Screen Shot 2022-04-05 at 4 15 33 PM](https://user-images.githubusercontent.com/21062119/161842973-08781b64-30af-470b-b912-eead0ad2e56e.png)
![Screen Shot 2022-04-05 at 4 15 19 PM](https://user-images.githubusercontent.com/21062119/161842981-a8400f52-15bd-4e58-a840-c0e777ed52a5.png)

Here I have @PREVENT-FUTUREDATE as an action tag but it lets me enter in a future date. PREVENT-PASTDATE has the same issue.

https://redcapstage.ctsi.ufl.edu/stage_c/redcap_v12.2.7/ExternalModules/manager/project.php?pid=18

REDCap version 12.2.7

**Comment by ChemiKyle** [comment] 2022-04-19 18:14
Problem originates from this line: https://github.com/ctsit/prevent_past_or_future_dates/blob/45935c99d41d3ed23c2c832699551e4bae26a387/js/preventPastOrFutureDates.js#L47

Escaped characters are now appearing in data:

```js
module = ExternalModules['PreventPastOrFutureDates'].ExternalModule;

module.tt('preventFutureDateFields')

// "[&quot;case_report_datetime&quot;,&quot;case_infection_area_date&quot;]"
```

Hacky fix:
```js
let preventPastDateFields = JSON.parse(module.tt('preventFutureDateFields').replace(/&quot;/g, '"'))
```

**Comment by mbentz-uf** [comment] 2022-04-25 20:26
This looks like a bug with REDCap external modules decoding `module.tt`.

**Comment by mbentz-uf** [comment] 2022-04-26 12:43
It's actually a bug in REDCap core `ExternalModules::tt_transferToJS` when objects are encoded. All applicable characters are converted to HTML entities using `htmlentities($val, ENT_QUOTES)`. Decoding the html javascript side fixes the issue. I'll also submit an issue on REDCap Consortium

**Comment by mbentz-uf** [comment] 2022-05-09 12:12
@ChemiKyle @ChemiKyle It's been confirmed this is a bug in REDCap itself. The fix should be in the next release https://community.projectredcap.org/questions/126891/externalmodulestt-transfertojs-converts-all-html-e.html

**Comment by pbchase** [comment] 2024-09-03 19:37
@saipavan10-git could you see if this bug exists anymore? If not, please just close this issue and PR #7

**Comment by saipavan10-git** [comment] 2024-09-16 21:12
@pbchase I tested the module today on Stage C with a test project, it functions as expected and I don't see the issue anymore.

**Closed** 2024-09-17 00:27 UTC
